# Generated by Django 5.1.3 on 2024-11-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='day',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='title',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='calories_burned',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
