# Generated by Django 5.1.3 on 2024-11-29 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_exerciseday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseDay',
        ),
    ]
