# Generated by Django 5.1.3 on 2024-11-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_remove_exercise_day_remove_exercise_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
