# Generated by Django 5.1.3 on 2024-11-29 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_remove_exercise_total_time_alter_exercise_date'),
        ('fitness', '0004_delete_exerciseday'),
    ]

    operations = [
    ]
