# Generated by Django 5.1.3 on 2024-11-30 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_alter_userprofile_user'),
        ('fitness', '0005_merge_20241129_1623'),
    ]

    operations = [
    ]
